# Configuration for running FCM test battery on Travis CI
# See https://travis-ci.org/ for more info.

---
language: perl

before_install:
    - cat >"${HOME}/.bashrc" <<<"export PATH=${PWD}/bin:\$PATH"
    - (echo 'passwd_gid_min=100' && echo 'passwd_uid_min=100') >'etc/fcm/admin.cfg'
    - source "${HOME}/.bashrc"
    # Ensure current user ID is not discarded by our email guess logic
    - sudo chfn -f "${USER}" "${USER}"

install: 
    - sudo apt-get install -y build-essential gfortran
    - sudo apt-get install -y libxml-parser-perl libconfig-inifiles-perl
    - sudo apt-get install -y libdbi-perl libdbd-sqlite3-perl
    # For some reason XML::Parser needs to be installed this way
    - cpanm 'Config::IniFiles' 'XML::Parser'
    # Latest Subversion
    - sudo sh -c 'echo "deb http://opensource.wandisco.com/ubuntu `lsb_release -cs` svn19" >> /etc/apt/sources.list.d/subversion19.list'
    - sudo wget -q http://opensource.wandisco.com/wandisco-debian.gpg -O- | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install -y subversion libsvn-perl python-subversion
    - sudo apt-get install -y heirloom-mailx
    - sudo apt-get install -y python-pip
    - sudo pip install trac

script: 
    - fcm test-battery -j 5
