#!/bin/bash
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2006-2013 Met Office.
#
# This file is part of FCM, tools for managing and building source code.
#
# FCM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FCM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FCM. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# NAME
#     fcm-rpmbuild
#
# SYNOPSIS
#     fcm-rpmbuild [--no-vcs] [SOURCE] [SOURCE_SITE]
#     E.g.:
#     fcm rpmbuild fcm:fcm/trunk fcm:fcm-site/trunk
#
# DESCRIPTION
#     Build an RPM for distributing FCM.
#
# OPTIONS
#     --no-vcs - do not add subversion and related dependencies to RPM.
#
# ARGUMENTS
#     SOURCE - The source tree of the distribution. (default = fcm:fcm/trunk)
#     SOURCE_SITE - The source tree with site specific settings in "etc/fcm/".
#-------------------------------------------------------------------------------

function get_last_changed_rev() {
    fcm info "$@" | awk -F': ' '$1 ~ /^Last Changed Rev$/ {print $2}'
}

set -eu
THIS=$(basename $0)

# Sort out the rpmbuild directory structure
if [[ -f $HOME/.rpmmacros ]]; then
    DIR=$(awk '$1 ~ /^%_topdir$/ {print $2}' $HOME/.rpmmacros)
    mkdir -p $DIR
else
    DIR=$(mktemp -d)
    echo "%_topdir $DIR" >$HOME/.rpmmacros
    function finally() {
        cd
        rm -f $HOME/.rpmmacros
        rm -rf $DIR
    }
    trap finally ERR
    trap finally EXIT
    trap finally INT
fi
cd $DIR
mkdir -p BUILD RPMS SOURCES SPECS SRPMS
rm -rf SOURCES/fcm

# Build RPM without no dependency on subversion or xxdiff?
REQUIRES_VCS="perl-Tk perl-XML-Parser subversion xxdiff"
if (($# > 0)) && [[ $1 == '--no-vcs' ]]; then
    REQUIRES_VCS=
    shift 1
fi

# Create the source tree
SOURCE=${1:-fcm:fcm/trunk}
fcm export -q $SOURCE SOURCES/fcm
REV_SOURCE="r$(get_last_changed_rev $SOURCE)"
SOURCE_SITE=${2:-}
REV_SOURCE_SITE=
if [[ -n $SOURCE_SITE ]]; then
    mkdir -p SOURCES/fcm-site/etc
    fcm export -q $SOURCE_SITE/etc/fcm SOURCES/fcm-site/etc/fcm
    cp -p SOURCES/fcm-site/etc/fcm/* SOURCES/fcm/etc/fcm/
    rm -r SOURCES/fcm-site
    REV_SOURCE_SITE="r$(get_last_changed_rev $SOURCE_SITE)"
fi
mkdir -p SOURCES/fcm/usr/local/bin
sed -i "s/\";$/$REV_SOURCE$REV_SOURCE_SITE\";/" SOURCES/fcm/doc/etc/fcm-version.js
cat >SOURCES/fcm/usr/local/bin/fcm <<'__FCM_WRAPPER__'
#!/bin/bash
FCM_HOME=${FCM_HOME:-/opt/fcm}
PATH=$FCM_HOME/bin:$PATH exec $FCM_HOME/bin/$(basename $0) "$@"
__FCM_WRAPPER__

# Create the rpmbuild spec file
chmod +x SOURCES/fcm/usr/local/bin/fcm
cat >SPECS/fcm.spec <<__SPEC__
Summary: FCM is a set of tools for managing and building source code.
Name: fcm
Version: $REV_SOURCE$REV_SOURCE_SITE
Release: 1
URL: http://www.metoffice.gov.uk/research/collaboration/fcm/
License: GPLv3
Group: Development/Tools
BuildRoot: $PWD/BUILD/%{name}-%{version}
BuildArch: noarch
Source: $PWD/SOURCES/fcm
Requires: diffutils gzip make perl perl-libwww-perl $REQUIRES_VCS

%description
http://www.metoffice.gov.uk/research/collaboration/fcm/

%prep

%build

%install
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT/opt/fcm
mkdir -p \$RPM_BUILD_ROOT/usr/local/bin
cd \$RPM_SOURCE_DIR
find fcm -type d -exec install -Dd {} \$RPM_BUILD_ROOT/opt/{} \;
find fcm -type f -exec install -D {} \$RPM_BUILD_ROOT/opt/{} \;
install \$RPM_SOURCE_DIR/fcm/usr/local/bin/fcm \$RPM_BUILD_ROOT/usr/local/bin/

%clean 
rm -rf \$RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
/usr/local/bin/fcm
/opt/fcm
__SPEC__

# Build the rpm
rpmbuild -ba SPECS/fcm.spec

cd $OLDPWD
cp $DIR/RPMS/noarch/* .
