#!/bin/bash
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2006-14 Met Office.
#
# This file is part of FCM, tools for managing and building source code.
#
# FCM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FCM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FCM. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# NAME
#     fcm-rpmbuild
#
# SYNOPSIS
#     fcm-rpmbuild [--no-gui] [REV]
#     E.g.:
#     fcm rpmbuild 2014-03
#
# DESCRIPTION
#     Build an RPM for distributing FCM.
#     Assume that the current working directory is a local Git clone containing
#     the FCM project.
#
# OPTIONS
#     --no-gui - do not add GUI packages such as "perl-Tk" and "xxdiff".
#
# ARGUMENTS
#     REV - Revision to build. Default to HEAD.
#-------------------------------------------------------------------------------

set -eu
THIS=$(basename $0)

rpmdev-setuptree

# Build RPM without no dependency on subversion or xxdiff?
REQUIRES_GUI='perl-Tk xxdiff'
if (($# > 0)) && [[ $1 == '--no-gui' ]]; then
    REQUIRES_GUI=
    shift 1
fi

# Create the source tree
REV=${1:-HEAD}
REV_NAME=$(git describe $REV)
REV_BASE=$(git describe --abbrev=0 $REV)
RELEASE=1
if [[ $REV_NAME != $REV_BASE ]]; then
    COMMIT_DATE=$(date -u +%Y%m%dT%H%M "--date=$(git show -s --format=%ci $REV)")
    RELEASE=${COMMIT_DATE}git${REV_NAME#$REV_BASE-*-g}
fi
REV_BASE_DOT=$(sed 's/-/./g' <<<$REV_BASE)
git archive --format=tar --prefix=fcm-$REV_BASE_DOT/ $REV \
    | (cd ~/rpmbuild/SOURCES/ && tar -xf -)
echo "FCM.VERSION=\"$REV_NAME\";" \
    >~/rpmbuild/SOURCES/fcm-$REV_BASE_DOT/doc/etc/fcm-version.js
rm -r ~/rpmbuild/SOURCES/fcm-$REV_BASE_DOT/{test,t}
if [[ -z $REQUIRES_GUI ]]; then
    rm ~/rpmbuild/SOURCES/fcm-$REV_BASE_DOT/{bin/fcm_gui,lib/FCM1/Interactive/InputGetter/GUI.pm}
fi

# Create the rpmbuild spec file
{
    cat <<__SPEC__
Name: fcm
Version: $REV_BASE_DOT
Release: $RELEASE
Summary: A modern Fortran build system + wrappers to SVN
Group: Development/Tools
License: GPLv3
URL: https://github.com/metomi/fcm/
Source0: https://github.com/metomi/fcm/releases/
BuildArch: noarch
Requires: diffutils gzip make perl-core perl-Config-IniFiles perl-MailTools perl-XML-Parser subversion subversion-perl $REQUIRES_GUI

%description
FCM: A modern Fortran build system + wrappers to Subversion for scientific
software development

%prep

%build

%install
rm -fr %{buildroot}
mkdir -p %{buildroot}/opt/
cp -pr %_sourcedir/fcm-$REV_BASE_DOT %{buildroot}/opt/fcm

%clean 
rm -fr %{buildroot}

%files
/opt/fcm
__SPEC__
} >~/rpmbuild/SPECS/fcm.spec

cd ~/rpmbuild/SPECS
rpmbuild -ba fcm.spec
rm -fr ~/rpmbuild/SOURCES/fcm-$REV_BASE_DOT
exit
