#!/usr/bin/perl
# ------------------------------------------------------------------------------
# (C) British Crown Copyright 2006-14 Met Office.
#
# This file is part of FCM, tools for managing and building source code.
#
# FCM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FCM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FCM. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";
use FCM::Admin::Commit qw{pre_commit_perm};

if (!caller()) {
    exit(pre_commit_perm(@ARGV));
}

1;
__END__

=head1 NAME

pre-commit-perm

=head1 SYNOPSIS

    pre-commit-perm REPOS TXN

=head1 ARGUMENTS

Accept the same arguments as a Subversion pre-commit hook.

=head1 DESCRIPTION

This program checks the commit rules by looking at whether the author has the
right to make the changes in the changeset.

=head1 COPYRIGHT

(C) Crown copyright Met Office. All rights reserved.

=cut
