#!/bin/bash
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2006-2012 Met Office.
#
# This file is part of FCM, tools for managing and building source code.
#
# FCM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FCM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FCM. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
set -eu

REPOS="$1"
TXN="$2"

REPOS_NAME=$(basename $REPOS)

# Check permission.
PERM_SCRIPT=$REPOS/hooks/svnperms.py
PERM_CONFIG=$REPOS/hooks/svnperms.conf
if [[ -x $PERM_SCRIPT && -a $PERM_CONFIG ]]; then
    $PERM_SCRIPT -r $REPOS -t $TXN -f $PERM_CONFIG
elif [[ -L $PERM_CONFIG ]]; then
    MESSAGE="ERROR: $REPOS_NAME: permission configuration file not found."
    echo $MESSAGE >&2
    svnlook author -t $TXN $REPOS \
        | sed 's/^/Author affected: /' \
        | mail -s"$MESSAGE" $(whoami)
    echo "The FCM team has been notified." >&2
    exit 1
fi

# Check size.
MB=1048576
THRESHOLD=10
SIZE_THRESHOLD_FILE=$0-size-threshold.conf
if [[ -f $SIZE_THRESHOLD_FILE && -r $SIZE_THRESHOLD_FILE ]]; then
    THRESHOLD=$(<$SIZE_THRESHOLD_FILE)
fi
SIZE=$(du -b -s $REPOS/db/txn-protorevs/$TXN.rev | cut -f 1)
if ((SIZE > THRESHOLD * MB)); then
    SIZE=$(du -h -s $REPOS/db/txn-protorevs/$TXN.rev | cut -f 1)
    echo "$REPOS_NAME@$TXN: changeset size ${SIZE}B exceeds ${THRESHOLD}MB." >&2
    echo "Contact the FCM team to bypass this restriction." >&2
    exit 1
fi

# Custom checking, if required
if [[ -f $0-custom && -x $0-custom ]]; then
    $0-custom "$@"
fi

# All checks passed, so allow the commit.
exit 0
