#!/bin/bash
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2006-2013 Met Office.
#
# This file is part of FCM, tools for managing and building source code.
#
# FCM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FCM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FCM. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
set -eu

REPOS="$1"
REV="$2"
USER="$3"
PROPNAME="$4"
ACTION="$5"

REPOS_NAME=${REPOS##*/}
if [[ $PROPNAME != 'svn:log' || $ACTION != 'M' ]]; then
    echo "$REPOS_NAME: can only modify svn:log property." >&2
    exit 1
fi

exit
