.\" Process this file with
.\" groff -man -Tascii fcm.1
.\"
.TH fcm 1 "" "" "User Commands"
.SH NAME
fcm - FCM, tools for managing and building source code.
.SH SYNOPSIS
.B fcm
.I command
[
.I options
] [
.I args
]
.SH OVERVIEW
.B fcm
is a set of tools for managing and building source code.
For full detail of the system, please refer to the FCM user guide, which you
should receive with this distribution.
.PP
Run "fcm help" to access the built-in tool documentation.
.SH AUTHOR
FCM Team <metomi@metoffice.gov.uk>.
Please feedback any bug reports or feature requests to us by e-mail.
.SH COPYRIGHT
\(co Copyright (C) British Crown (Met Office) & Contributors.
.PP
FCM is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.PP
FCM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with FCM. If not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.BR svn (1),
.BR perl (1)
